on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

defaults:
  run:
    shell: bash

jobs:
  build_jar:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install java 17 ubuntu
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'

      - name: testing
        run: |
          ./gradlew test
        
      - name: build
        run: |
          ./gradlew build

      - name: build docker
        id: build_docker
        run: |
          docker_env="dev"
          if [ ${{ github.ref_name }} == "main" ]; then
            docker_env="prod"
          fi
          docker build -t jecalad/testing:$docker_env .
          echo "docker_env=$docker_env" >> $GITHUB_OUTPUT

      - name: docker login
        if: ${{ github.ref_name == 'main' || github.ref_name == 'dev' }}
        run: |
          docker login -u jecalad -p ${{ secrets.docker_token }}  
          docker push jecalad/testing:${{ steps.build_docker.outputs.docker_env }}