on:
  push:

defaults:
  run:
    shell: bash

jobs:
  build_jar:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        
      - name: build
        run: |
          ./gradlew build

      - name: build docker
        run: |
          docker build -t jecalad/testing:latest
          docker push ecalad/testing:latest